### PR TITLE
add tbuilder to builder-registrations

### PR DESCRIPTION
**Pull request by EshanTbuilder**
Please refer to tbuilder.xyz for the documentation.

### CODE REVIEW

**Comment by EshanTbuilder** [comment]
we tbuilder agree to adhere to the fair market principles.

**Comment by TymKh** [comment]
@EshanTbuilder could you please confirm that you are receiving bundles? Tx example that you should've received: https://etherscan.io/tx/0xecb270408f560fe159dbfcaaf52ce89c6b17d403ed2e3fd3677f140f1710f877

**Comment by EshanTbuilder** [comment]
I have been receiving bundles.
Assume these headers are there because its from you guys.
```
"X-Flashbots-Signature": "0x758aC3DC8FB6F939adf42bB83e717f94619052f5:0x95584f22f8765ee808363c632104c3718880a333b88dd9d426717113f9677b85391b1316f478d08a34d447e11a46afb2d1cc1ea3e46434c2ef2eff222c48af8101"
```

**Comment by TymKh** [comment]
Hm, you should only receive `x-orderflow-origin: flashbots` header. Do you receive other headers as well?

**Comment by EshanTbuilder** [comment]
Yea I got that as well.
```
"Content-Length": "528", 
"Accept": "application/json", 
"X-Orderflow-Origin": "flashbots", 
"Content-Type": "application/json", 
"Accept-Encoding": "gzip", 
"User-Agent": "Go-http-client/2.0"
```

**Comment by EshanTbuilder** [comment]
> Hm, you should only receive `x-orderflow-origin: flashbots` header. Do you receive other headers as well? сс: @EshanTbuilder

Yea I got that as well.
```
"Content-Length": "528", 
"Accept": "application/json", 
"X-Orderflow-Origin": "flashbots", 
"Content-Type": "application/json", 
"Accept-Encoding": "gzip", 
"User-Agent": "Go-http-client/2.0"
```

**Pull request merged**
